version: '3'

services:
  yap:
    build: ./config/docker/nodejs
    container_name: youtube_audio_player
    environment:
      - LOCAL_USER_ID=$USER_ID
    ports:
      - 8081:8081
      - 3000:3000
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $PWD:/app
    privileged: true
